name: worktime
description: Aplicación de fichaje laboral
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Gestión de estado
  provider: ^6.1.2

  # Navegación
  go_router: ^14.6.2

  # Gráficas
  fl_chart: ^0.70.1

  # Internacionalización
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true